[package]
name = "ishihara"
version = "0.1.0"
authors = ["Brennan Tracy <brennantracy4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.1"
rand = "0.8.3"
rusttype = "0.9.2"
image = "0.23.12"
imageproc = "0.22.0"
