[workspace]

members = [
    "ishihara",
	"wasm-game-of-life",
	"root",
	"mandelbrot",
]

[package]
name = "brongan-com"
version = "0.1.0"
authors = ["Brennan Tracy <brennantracy4@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-logger = "0.2"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
root = { path = "root" }
