[package]
name = "wasm-game-of-life"
version = "0.1.0"
authors = ["Brennan Tracy <brennantracy4@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fixedbitset = "0.4"
getrandom = { version = "0.2", features = ["js"] }
gloo-render = "0.1"
js-sys = "0.3"
log = "0.4"
rand = "0.8"
wasm-bindgen = "0.2"
wasm-logger = "0.2"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }

[dev-dependencies]
criterion = "^0.3"
pprof = { version = "^0.3", features = ["flamegraph"] }

[profile.release]
debug = true # gimme those unstripped binaries
opt-level = "s" # Tell `rustc` to optimize for small code size.

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  'Document',
  'DomRect',
  'Element',
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGlRenderingContext',
  'WebGlShader',
  'WebGlTexture',
  'WebGlUniformLocation',
  'Window',
]
