# fly.toml file generated for late-wood-6224 on 2023-05-16T01:19:59-07:00

app = "late-wood-6224"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sea"
processes = []

[restart]
policy = "no"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
