# fly.toml file generated for still-lake-5553 on 2023-05-05T18:35:34-07:00

app = "still-lake-5553"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"

[restart]
policy = "no"

[[services]]
  protocol = "tcp"
  internal_port = 8043
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443   soft_limit = 20
